"""empty message

Revision ID: 0dd416463f04
Revises: 67b3d9d9b73f
Create Date: 2019-03-21 10:43:33.366354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dd416463f04'
down_revision = '67b3d9d9b73f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cust_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=32), nullable=True),
    sa.Column('time', sa.String(length=32), nullable=True),
    sa.Column('party', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['cust_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservations')
    # ### end Alembic commands ###
