"""empty message

Revision ID: 5f81300e98dd
Revises: e3c38d00d77e
Create Date: 2019-03-20 13:30:49.392975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f81300e98dd'
down_revision = 'e3c38d00d77e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=32), nullable=True),
    sa.Column('time', sa.String(length=32), nullable=True),
    sa.Column('party', sa.String(length=32), nullable=True),
    sa.Column('cust_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cust_id'], ['customers.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'cust_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservations')
    # ### end Alembic commands ###
