"""empty message

Revision ID: 69799b785e40
Revises: 5f81300e98dd
Create Date: 2019-03-20 13:38:15.068104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69799b785e40'
down_revision = '5f81300e98dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reservations_cust_id_fkey', 'reservations', type_='foreignkey')
    op.drop_column('reservations', 'cust_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('cust_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('reservations_cust_id_fkey', 'reservations', 'customers', ['cust_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
