"""empty message

Revision ID: 9bee782d5c72
Revises: b5aaa346f45d
Create Date: 2019-03-18 14:33:12.225219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bee782d5c72'
down_revision = 'b5aaa346f45d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('orders_contain')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders_contain',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name='orders_contain_item_id_fkey'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='orders_contain_order_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='orders_contain_pkey')
    )
    op.drop_table('order_items')
    # ### end Alembic commands ###
