"""empty message

Revision ID: 9bf5da0d7ef4
Revises: 0dd416463f04
Create Date: 2019-03-21 13:17:16.291176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bf5da0d7ef4'
down_revision = '0dd416463f04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'active')
    # ### end Alembic commands ###
