"""empty message

Revision ID: e253ee37986d
Revises: 69799b785e40
Create Date: 2019-03-20 13:44:49.615143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e253ee37986d'
down_revision = '69799b785e40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('cust_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reservations', 'customers', ['cust_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.drop_column('reservations', 'cust_id')
    # ### end Alembic commands ###
