"""empty message

Revision ID: 393789f720a7
Revises: 0dd416463f04
Create Date: 2019-03-21 11:55:22.498992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '393789f720a7'
down_revision = '0dd416463f04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('active', sa.Boolean(), nullable=True))
    op.alter_column('orders', 'cust_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'cust_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('items', 'active')
    # ### end Alembic commands ###
