"""empty message

Revision ID: 46b05022d86b
Revises: 75d00484181f
Create Date: 2019-03-21 10:14:53.436271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46b05022d86b'
down_revision = '75d00484181f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('reservations', 'res_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('res_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('reservations', 'id')
    # ### end Alembic commands ###
