"""empty message

Revision ID: 67b3d9d9b73f
Revises: 46b05022d86b
Create Date: 2019-03-21 10:17:26.860819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67b3d9d9b73f'
down_revision = '46b05022d86b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cust_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=32), nullable=True),
    sa.Column('time', sa.String(length=32), nullable=True),
    sa.Column('party', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['cust_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservations')
    # ### end Alembic commands ###
