"""empty message

Revision ID: 75d00484181f
Revises: 39b79e8b1d05
Create Date: 2019-03-21 09:49:26.595037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d00484181f'
down_revision = '39b79e8b1d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('res_id', sa.Integer(), nullable=False))
    op.drop_column('reservations', 'id')
    sa.PrimaryKeyConstraint('res_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('reservations', 'res_id')
    # ### end Alembic commands ###
