"""empty message

Revision ID: ce66d77e8a63
Revises: 25497ae8ae66
Create Date: 2019-03-18 22:03:04.923521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce66d77e8a63'
down_revision = '25497ae8ae66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pay_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('orders_empl_id_fkey', 'orders', type_='foreignkey')
    op.drop_table('employee')
    op.create_foreign_key(None, 'orders', 'employees', ['empl_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_empl_id_fkey', 'orders', 'employee', ['empl_id'], ['id'])
    op.create_table('employee',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('pay_rate', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='employee_pkey')
    )
    op.drop_table('employees')
    # ### end Alembic commands ###
