"""empty message

Revision ID: cfb635d9b172
Revises: 339748f86335
Create Date: 2019-03-21 00:44:50.381285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb635d9b172'
down_revision = '339748f86335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('cust_id', sa.Integer(), nullable=True))
    op.drop_constraint('reservations_id_fkey', 'reservations', type_='foreignkey')
    op.create_foreign_key(None, 'reservations', 'customers', ['cust_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.create_foreign_key('reservations_id_fkey', 'reservations', 'customers', ['id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('reservations', 'cust_id')
    # ### end Alembic commands ###
