"""empty message

Revision ID: e3c38d00d77e
Revises: 224d552285d8
Create Date: 2019-03-19 12:06:20.368123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3c38d00d77e'
down_revision = '224d552285d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'empl_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'empl_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
