"""empty message

Revision ID: f446b9619bae
Revises: cfb635d9b172
Create Date: 2019-03-21 09:16:51.014029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f446b9619bae'
down_revision = 'cfb635d9b172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'cust_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'cust_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
